src/main/java/com/ludo/study/studymatchingplatform/common/entity/BaseEntity.java, src/main/java/com/ludo/study/studymatchingplatform/user/controller/UserController.java, src/main/java/com/ludo/study/studymatchingplatform/user/service/UserService.java
회원 탈퇴 기능을 추가하였습니다.
현재 구현된 코드의 정책은 다음과 같습니다.
1. 회원 탈퇴는 기본적으로 soft delete로 진행한다.
2. 회원 탈퇴된 계정은 실제 DB에서 제거되는 것이 아니며, **정해진 기간**동안 사용자의 의향에 따라 복구가 가능하다.
3. 이미 탈퇴한 계정으로 탈퇴를 시도하는 경우
-> 복구가 불가능하기 때문에 404 NotFound
4. 비활성화 된 계정으로 탈퇴를 시도하는 경우
-> 이미 soft delete 처리된 계정에 대한 충돌이므로, 회원 가입을 재시도 하여 계정을 복구하라는 오류와 함께 409 Conflict
5. 탈퇴 성공 시
-204 NoContent -> res body가 없는 성공이므로. 향후 응답 공통 템플릿이 완성되면 변경 가능성O
=> SP-349/Feat: 회원 탈퇴 기능 추가

.idea/modules/com.ludo.study.study-matching-platform.main.iml, src/main/java/com/ludo/study/studymatchingplatform/study/domain/Platform.java, src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyCreateService.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/request/WriteStudyRequest.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/WriteStudyResponse.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/CreateStudyServiceTest.java
- 스터디 생성시 요청 / 응답 항목 추가했습니다.
- 스터디 생성에 대한 테스트 케이스를 작성했습니다.
<br><br>
```java
@Builder
public record WriteStudyRequest(
String title,
Long categoryId,
Long positionId, // mypage API PR과 통합되면 정상 작동 합니다.
Way way,
Platform platform,
Integer participantLimit,
LocalDateTime startDateTime,
LocalDateTime endDateTime
) {
@Builder
public record WriteStudyResponse(
Long id,
StudyStatus status,
CategoryResponse category,
UserResponse owner,
String title,
Platform platform,
List<ParticipantResponse> participants,
Way way,
Integer participantLimit,
Integer participantCount,
LocalDateTime startDateTime,
LocalDateTime endDateTime
) {
```
- **Way와 같은 맥락이라고 생각하여 Enum으로 구현했습니다.**
```java
@Entity
@Getter
@SuperBuilder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
public class Study …
```
=> Sp 213/Refactor: 스터디 생성시 항목 추가

src/main/java/com/ludo/study/studymatchingplatform/study/Participant.java, src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Recruitment.java, src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/RecruitmentPosition.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/RecruitmentPositionService.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/RecruitmentService.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/RecruitmentStackService.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/RecruitmentPositionServiceTest.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/RecruitmentServiceTestBakup.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/RecruitmentsFindServiceTest.java
모집 공고 수정에 대한 API 작성
모집 공고 수정 시 입력된 Position, Stack에 따라 Link table이 제거 or 추가되어야 합니다.
이를 위해 다음과 같은 서비스가 추가되었습니다.
`RecruitmentStackService`도 거의 비슷하므로 생략합니다.
```java
public class RecruitmentPositionService {
// ...
public void addMany(final Recruitment recruitment, final Set<Long> positionIds) {
final List<Position> positions = positionService.findAllByIdsOrThrow(positionIds);
addRecruitmentPositionsIn(recruitment, positions);
}
public void update(final Recruitment recruitment, final Set<Long> positionIds) {
final Set<Position> nextPositions = positionRepository.findByIdIn(positionIds);
final List<Position> addedPositions = recruitment.getAddedPositions(nextPositions);
addRecruitmentPositionsIn(recruitment, addedPositions);
recruitment.removeRecruitmentPositionsNotIn(nextPositions);
}
private …
```
=> feature: 모집 공고 수정 및 Recruitment 연결 테이블 관련 테스트

src/main/java/com/ludo/study/studymatchingplatform/auth/common/AuthController.java
인증/인가 수단이 Cookie로 완전히 정해지기 전에 임시로 작성해두어 `logout` 핸들러가 실제 경로와 Mapping 되어 있지 않았습니다.
```java
@PostMapping("/auth/logout")
public void logout(final HttpServletResponse response) throws IOException {
cookieProvider.clearAuthCookie(response);
redirection.to("/", response);
}
```
`logout` Handler를 `PostMapping`으로 실제 경로와 매핑하였습니다.
추가된 코드는 `@PostMapping("/auth/logout")` 한 줄입니다.
=> hotfix: Route Logout Handler

src/main/java/com/ludo/study/studymatchingplatform/study/repository/CategoryRepositoryImpl.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/PositionRepositoryImpl.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/StudyApplicantDecisionServiceTest.java
- 최신화 된 main 브랜치에서 기존 테스트가 컴파일 오류 발생하는 문제가 있어요.
```java
// before
@Transactional
public ParticipantResponse applicantAccept(final User owner, final StudyApplicantDecisionRequest request) {
final Study study = findStudy(request.studyId());
final User applicantUser = findUser(request.applicantUserId());
study.acceptApplicant(owner, applicantUser, request.recruitmentId());
Participant participant = findParticipant(study, applicantUser);
return Participant.from(participant);
}
// after
@Transactional
public ApplyAcceptResponse applicantAccept(final User owner, final StudyApplicantDecisionRequest request) {
final Study study = findStudy(request.studyId());
final User applicantUser = findUser(request.applicantUserId());
study.acceptApplicant(owner, applicantUser, request.recruitmentId()); …
```
=> Hotfix: 지원자 수락 서비스 계층 반환 타입 변경으로 인한 기존 테스트 컴파일 오류 해결

src/main/java/com/ludo/study/studymatchingplatform/user/controller/UserController.java, src/main/java/com/ludo/study/studymatchingplatform/user/domain/User.java, src/main/java/com/ludo/study/studymatchingplatform/user/domain/exception/CurrentNicknameEqualsException.java, src/main/java/com/ludo/study/studymatchingplatform/user/domain/exception/DuplicateNicknameException.java, src/main/java/com/ludo/study/studymatchingplatform/user/repository/UserRepositoryImpl.java, src/main/java/com/ludo/study/studymatchingplatform/user/service/ChangeNicknameService.java, src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/request/ChangeUserNicknameRequest.java, src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/response/ChangeUserNicknameResponse.java, src/test/java/com/ludo/study/studymatchingplatform/user/service/ChangeNicknameServiceTest.java
<br><br>
**닉네임 변경 시, 현재 닉네임으로는 변경할 수 없다** 라는 **도메인 요구사항을 코드로 명시**하기 위해
아래와 같이 changeNickname 메서드 내부에 검증 로직을 포함시켰어요.
```java
// User Domain Entity
public void changeNickname(final String nickname) {
validateNotEqualsCurrentNickname(nickname);
this.nickname = nickname;
}
```
<br><br>
```java
// Service
@Transactional
public ChangeUserNicknameResponse changeUserNickname(final User user, final String changeNickname) {
user.validateNotEqualsCurrentNickname(changeNickname); // 현재 닉네임과 동일여부 검증
validateDuplicateNickname(changeNickname); //  중복 닉네임 검증
user.changeNickname(changeNickname);
return new ChangeUserNicknameResponse(user);
}
private void validateDuplicateNickname(final String nickname) {
if (userRepository.existsByNickname(nickname)) { // repository 호출 → DB I/O 발생
throw new …
```
=> SP-350/Feat: 사용자 닉네임 변경

src/main/java/com/ludo/study/studymatchingplatform/auth/google/service/GoogleSignUpService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/kakao/service/KakaoSignUpService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/naver/service/NaverSignUpService.java, src/main/java/com/ludo/study/studymatchingplatform/user/domain/User.java, src/main/java/com/ludo/study/studymatchingplatform/user/domain/exception/UserExceptionMessage.java, src/test/java/com/ludo/study/studymatchingplatform/user/domain/UserTest.java
<br><br>
```java
public class User {
public static final String DEFAULT_NICKNAME_PREFIX = "스따-디 %d";
public static final Long DEFAULT_NICKNAME_ID = 716L;
public void setInitialDefaultNickname() {
validateInitDefaultNickname();
this.nickname = String.format(DEFAULT_NICKNAME_PREFIX, DEFAULT_NICKNAME_ID + id);
}
private void validateInitDefaultNickname() {
if (this.id == null) {
throw new IllegalArgumentException(UserExceptionMessage.INIT_DEFAULT_NICKNAME.getMessage());
}
}
}
```
- 기본 닉네임 설정 시, 아이디 값이 존재해야 한다는 **비즈니스 요구사항을 도메인 로직 코드로 반영**하고자 했어요.
- `setInitialDefaultNickname` 을 **호출할 때 마다, `String.format`을 호출**해야 하는 점이 아쉬움으로 남았어요.
- `DEFAULT_NICKNAME_PREFIX`, `DEFAULT_NICKNAME_ID` 상수를 User Domain Entity에서 관리하는게 적합한 구조인지 애매하다는 판단이 들어요. 별도의 **Config Enum 으로 관리**하면 좋을 듯 싶은데, 피드백 주시면 반영해볼게요. …
=> SP-357/Feat: 소셜 회원가입 시 중복되지 않는 기본 닉네임 부여

src/main/java/com/ludo/study/studymatchingplatform/study/controller/RecruitmentController.java, src/main/java/com/ludo/study/studymatchingplatform/study/controller/StudyController.java, src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyApplicantDecisionService.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/request/StudyApplicantDecisionRequest.java, src/test/java/com/ludo/study/studymatchingplatform/study/domain/StudyTest.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/StudyApplicantDecisionServiceTest.java
관련 PR: https://github.com/Ludo-SMP/ludo-backend/pull/30
<br><br>
**스터디 지원자 수락, 거절 메서드 시그니쳐** 변경사항은 다음과 같아요.
```java
// before
public void acceptApplicant(final User owner, final User applicantUser, final Long recruitmentId) {
}
public void rejectApplicant(final User owner, final User applicantUser, final Long recruitmentId) {
}
```
```java
// after
public void acceptApplicant(final User owner, final User applicantUser) {
}
public void rejectApplicant(final User owner, final User applicantUser) {
}
```
- **`Study` Domain 은 `Recruitment` Domain을 인스턴스 필드로 갖고있기 때문에** 사실 `Long recruitmentId` 는 필요 없어요.
- 구현을 하면서도 `Long recruitmentId` 존재에 어색함을 느꼈는데 이 문제가 해결 되었어요. @Hugh-KR 좋은 의견 감사합니다 👍
<br> <br>
- 처음에 설계한 API명세는 `/api/studies/{study-id}/recruitments/{recruitment-id}/apply-accept/{applicantUserId} …
=> SP-324/Fix: 스터디 지원 수락 / 거절 API 명세 수정 반영

src/main/java/com/ludo/study/studymatchingplatform/config/DataInitializer.java, src/main/java/com/ludo/study/studymatchingplatform/study/controller/RecruitmentController.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/dto/request/PopularRecruitmentCond.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/RecruitmentRepositoryImpl.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/PopularRecruitmentsFindService.java, src/test/java/com/ludo/study/studymatchingplatform/study/fixture/CategoryFixture.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/PopularRecruitmentsFindServiceTest.java
- https://github.com/Ludo-SMP/ludo-backend/issues/65
<br><br>
- 코딩테스트 → 코딩 테스트
- 모의면접 → 모의 면접
```java
@Transactional
public PopularRecruitmentsResponse findPopularRecruitments(final PopularRecruitmentCond cond) {
List<Recruitment> popularCoding = recruitmentRepository.findPopularRecruitments("코딩 테스트", cond);
List<Recruitment> popularInterview = recruitmentRepository.findPopularRecruitments("모의 면접", cond);
List<Recruitment> popularProject = recruitmentRepository.findPopularRecruitments("프로젝트", cond);
return new PopularRecruitmentsResponse(
recruitmentPreviewResponseMapper.mapBy(popularCoding),
recruitmentPreviewResponseMapper.mapBy(popularInterview),
recruitmentPreviewResponseMapper.mapBy(popularProject)
);
}
```
하지만 **데이터 컬럼 내용이 바뀔 때마다 코드 수정이 이루어져야하는 단점**이 있어요. 이렇게 구현한 이유는 아래 논의 사항에 …
=> SP-218/Fix: 인기 모집 공고 목록 조회 기능 수정

src/main/java/com/ludo/study/studymatchingplatform/auth/common/AuthController.java, src/main/java/com/ludo/study/studymatchingplatform/common/advice/CommonResponse.java, src/main/java/com/ludo/study/studymatchingplatform/common/advice/CommonResponseAdvice.java, src/main/java/com/ludo/study/studymatchingplatform/common/annotation/DataFieldName.java, src/main/java/com/ludo/study/studymatchingplatform/common/exception/GlobalExceptionHandler.java, src/main/java/com/ludo/study/studymatchingplatform/study/controller/RecruitmentController.java, src/main/java/com/ludo/study/studymatchingplatform/study/controller/StackController.java, src/main/java/com/ludo/study/studymatchingplatform/study/controller/StudyController.java, src/main/java/com/ludo/study/studymatchingplatform/user/controller/MyPageController.java, src/main/java/com/ludo/study/studymatchingplatform/user/controller/UserController.java
Controller Layer에서 `Response`를 내보낼 때 형식 통일을 위해 `ResponseEntity<BaseApiResponse<T>>` 형식의 코드가 중복되는 현상을 제거하였으며, Annotation을 통해 약간의 Swagger 문서를 추가 하였습니다.
```java
@PostMapping
@ResponseStatus(HttpStatus.CREATED)
@DataFieldName("study")
@Operation(description = "스터디 생성")
@ApiResponse(description = "스터디 생성 성공", responseCode = "201", useReturnTypeSchema = true, content = @Content(mediaType = "application/json"))
public StudyResponse create(@RequestBody final WriteStudyRequest request,
@Parameter(hidden = true) @AuthUser final User user) {
final Study study = studyCreateService.create(request, user);
return StudyResponse.from(study);
}
```
<br><br>
아래 코드를 통해 Controller Layer에서의 처리가 완료되고 실제 Serialization이 발생하기 전, `Response Body`에 삽입될 데이터의 형식을 바꿔주도록 후속 작업을 해줍니다.
Controller에서 반환된 타입명은 …
=> SP-373/Refactor: Controller Response 일반화 및 문서화

src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/response/ApplicantRecruitmentResponse.java, src/test/java/com/ludo/study/studymatchingplatform/user/service/MyPageServiceTest.java
- 지원 취소시 사용할 studyId 추가
<br><br>
=> SP-348/Refactor: 마이 페이지, 내가 지원한 스터디 목록 항목 추가

src/main/java/com/ludo/study/studymatchingplatform/auth/controller/naver/NaverLoginController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/controller/naver/NaverSignUpController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/naver/NaverLoginService.java
- (액세스 토큰을 쿠키에 담아 보내주기 때문이에요.)
- 현재 글로벌 예외 핸들러는 `IllegalArugmentException`은 메인 페이지로 리다이렉트를 추가하는 기능을 수행하고 있습니다.
- 현재 비즈니스 요구사항에 로그인 실패 시, 메인 페이지 리다이렉트가 아닌 예외 모달을 띄워주는 방식으므로, 예외를 그에 맞게 변경했습니다.
<br><br>
- [o] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [o] 커밋 메세지를 컨벤션에 맞추었습니다.
- [o] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [o] 변경 후 코드는 기존의 테스트를 통과합니다.
- [o] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [o] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.
=> SP-234/Fix: 네이버 소셜 로그인 로직 변경

src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Recruitment.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/applicant/ApplicantRepositoryImpl.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/study/participant/ParticipantRepositoryImpl.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/study/StudyResponse.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/applicant/StudyApplicantDecisionServiceTest.java
- 스터디 지원자 수락 / 거부시 softdelete 처리하여 목록에서 제외 되도록 변경 했습니다.
- 적용하며 어긋난 테스트를 수정하여 정상 동작하도록 리팩터링 진행했습니다 아래 링크 참고 부탁드려요.
[SP-380 test: 스터디 지원자 수락 / 거부시 softdelete 처리를 반영한 기존 테스트 코드 수정](https://github.com/Ludo-SMP/ludo-backend/commit/1d4598eb76e170dbc35148c7a90e2e0f29073177) 
- 스터디 탈퇴시 스터디 상태 페이지와 마이 페이지에서 participant의 softdelete 처리된 항목을 제외하고 표시하도록 변경했습니다.
<br><br>
- **스터디 지원자 수락 / 거부시 softdelete 처리 소스 코드 입니다.**
<br><br>
- **스터디 탈퇴시 스터디 상태 페이지와 마이 페이지에서 participant의 softdelete 처리된 항목을 제외하고 표시하도록 하는 소스 코드 입니다.**
<br><br>
=> Sp 380/Refactor: 스터디 지원자 수락 / 거부시 지원자 목록에서 제외, 스터디 탈퇴한 참여자 상태 페이지 / 마이 페이지에서 제외

src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Recruitment.java, src/main/java/com/ludo/study/studymatchingplatform/study/domain/study/Study.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/applicant/ApplicantRepositoryImpl.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentService.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/study/StudyCreateService.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/study/StudyFetchService.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/study/StudyUpdateService.java, src/main/java/com/ludo/study/studymatchingplatform/user/controller/MyPageController.java, src/main/java/com/ludo/study/studymatchingplatform/user/service/MyPageService.java, src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/response/MyPageResponse.java, src/test/java/com/ludo/study/studymatchingplatform/study/fixture/recruitment/applicant/ApplicantFixture.java, src/test/java/com/ludo/study/studymatchingplatform/user/service/MyPageServiceTest.java
- **모집 공고 지원자 거절시 softdelete 되는 시점을 지원 기록 삭제 시로 변경했습니다.**
- **지원 기록 삭제 메서드의 위치를 변경했습니다.**
- recruitmentService -> mypageService
- **테스트 케이스의 불변을 유지하기 위해서 endDateTime 시점에 따른 스터디 상태 변경 시점을 변경했습니다.**
- LocalDateTime.now() 선언 시점, domain -> service
<br><br>
- 모집 공고 생성 후 지원자가 없는 상태에서 `지원자 확인 버튼`이 활성화 되는 예외는 아직 손대지 않았습니다. 이유는 `아직 지원자가 없어요` 라는 상태를 띄워 주는것이 조금 더 자연스럽지 않을까 하는 생각 때문인데, 오늘 데일리 스크럼에서 이야기 나누고 확정된 사안을 반영하도록 하겠습니다. 
<br><br>
=> Sp-348/Hotfix: 모집 공고 지원자 거절시 softdelete 되는 시점을 지원 기록 삭제 시로 변경

src/main/java/com/ludo/study/studymatchingplatform/auth/service/google/GoogleLoginService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/google/GoogleProfileRequestService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/google/GoogleSignUpService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/google/vo/GoogleUserProfile.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/kakao/dto/response/KakaoUserProfile.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/naver/NaverLoginService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/naver/NaverProfileRequestService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/naver/NaverSignUpService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/naver/vo/NaverUserProfile.java, src/main/java/com/ludo/study/studymatchingplatform/user/domain/user/User.java
<br><br>
```java
// User Entity
@Column
@Size(min = 1, max = 20)
private String nickname;
```
- 저희 서비스의 닉네임은 `prefix문자` + `기본숫자값` + `user_id (auto_increment)`로 지정됩니다.
- 즉 기본 닉네임을 부여하기 위해선 User 레코드를 한 번 삽입해야 합니다.
- 삽입 이전엔 nickname 이 null 이므로, `nullable = false`에 의해 insert 쿼리에서 오류가 발생합니다.
- `nickname = ""` 와 같은 방식으로 빈문자열로 초기화하여 넣어줄 수도 있지만, 불 필요한 코스트라 생각하여 `nullable = true`로 제약 조건을 변경했습니다.
<br> <br>
- Naver 뿐만 아니라 Google, Kakao도 유저 프로필 응답값의 nickname을 제거했습니다. 후속 작업으로 카카오, 구글 로그인 Open API 사용자 프로필 수집 항목 중 `닉네임`을 제거해야 하기 때문에 일괄 처리했습니다.
<br><br>
- 카카오, 구글 로그인 Open API 사용자 프로필 수집 항목 중 `닉네임` 제거
- MyPageServiceTest 테스트 실패 문제 해결 필요
<br><br>
- [o] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [o] 커밋 메세지를 컨벤션에 맞추었습니다.
- [o] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [_] 변경 후 코드는 기존의 테스트를 …
=> SP-234/Fix: 소셜 로그인 사용자 프로필 수집 대상 변경으로 인한 코드 수정

src/main/java/com/ludo/study/studymatchingplatform/auth/service/google/GoogleLoginService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/google/GoogleSignUpService.java, src/main/java/com/ludo/study/studymatchingplatform/common/exception/GlobalExceptionHandler.java, src/main/java/com/ludo/study/studymatchingplatform/config/DataInitializer.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/applicant/ApplicantRepositoryImpl.java
- [refactor: 구글 로그인 / 회원가입 예외 전역 처리](https://github.com/Ludo-SMP/ludo-backend/commit/4287cf556662d5be165244ec78c952d6555cde99)
- [refactor: 로그인 / 회원가입 예외 페이지 리다이렉션 적용](https://github.com/Ludo-SMP/ludo-backend/commit/deff464dfef150f09de902a619e576afcfea2430)
- [refactor: 스터디 지원자 거절시 목록에서 제거 로직 추가](https://github.com/Ludo-SMP/ludo-backend/commit/dfe922de639cce943e7a51a70d34683b6275a6d4)
- [refactor: DataInitializer, 주석 처리](https://github.com/Ludo-SMP/ludo-backend/pull/98/commits/2f9c40a8e4aa551ca8d9fc1b296c62beb38726ae)
<br><br>
- **구글 로그인 / 회원가입 예외시 전역처리 하도록 변경했습니다.**
<br><br>
- **로그인 / 회원가입 예외 페이지 리다이렉션을 적용했습니다.**
<br><br>
- **지원자 거절시 목록에서 지워주도록 하는 로직을 추가했습니다.**
<br><br>
- **DataInitializer클래스가 동작하지 않도록 주석 처리 했습니다.**
=> Sp-235/Hotfix: 구글 로그인 / 회원가입 예외 전역 처리, 스터디 지원자 거절시 목록에서 제거 로직 추가

src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Recruitment.java, src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/RecruitmentRepositoryImpl.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentDetailFindServiceTest.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentServiceTest.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentsFindServiceTest.java
<br> <br>
- 기존의 `updatedDateTime` 컬럼은 **변경 감지가 발생할 때 마다** 수정 날짜가 갱신되는 구조에요.
```java
@Getter
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {
@LastModifiedDate
@Column(nullable = false)
private LocalDateTime updatedDateTime;
// something ..
}
```
<br> <br>
```java
public List<Recruitment> findRecruitments(final RecruitmentFindCursor recruitmentFindCursor,
final RecruitmentFindCond recruitmentFindCond) {
JPAQuery<Recruitment> recruitmentTable = q.select(recruitment)
.from(recruitment);
// 동적 조인 코드 생략
return recruitmentTable
.where(
eqCategory(recruitmentFindCond.categoryId()),
eqWay(recruitmentFindCond.way()),
eqPosition(recruitmentFindCond.positionId()),
eqStack(recruitmentFindCond.stackIds()))
.where(lessThan(recruitmentFindCursor.last())) …
```
=> SP-210/Fix: `모집 공고 상세 조회`, `스터디 지원`시 모집 공고 목록 조회 순서가 바뀌는 이슈 해결

src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Recruitment.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentServiceTest.java
<br><br>
`기존`
```java
@Entity
public class Recruitment extends BaseEntity {
@Builder.Default
private LocalDateTime modifiedDateTime = LocalDateTime.now();
}
```
`변경후`
```java
@Entity
public class Recruitment extends BaseEntity {
@CreatedDate
@Column(nullable = false)
private LocalDateTime modifiedDateTime;
}
```
**문제상황**
기존 로직에서는 아래와 같이 `수정날짜(modifiedDateTime)`이 `생성날짜(createdDateTime)` 보다 이전인 예외가 발생합니다.
**이유**
- `수정날짜(modifiedDateTime)`는 객체를 생성하는 시점에 초기화됩니다.
- `생성날짜(createdDateTime)`는 JPA Auditing에 의해 객체를 `insert` 하는 시점에 초기화됩니다.
- 따라서 수정날짜가 생성날짜보다 ms 단위로 앞서게 됩니다.
**해결**
- `수정날짜(modifiedDateTime)`에도 JPA Auditing 기능을 이용하여 @CreatedDate 를 적용했습니다.
- 이전 회의에서 적용이 안될 것으로 예측했지만, Recruitment 는 BaseEntity를 상속받고 있고 그에 따라 **@EntityListeners(AuditingEntityListener.class) 애노테이션도 함께 상속**받으므로 적용이 가능합니다. …
=> Fix: 모집공고 수정날짜가 생성날짜보다 이전 날짜로 기록되는 문제 해결

src/test/java/com/ludo/study/studymatchingplatform/config/DbInitializer.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/PopularRecruitmentsFindServiceTest.java
- @PostConstructor 데이터 삽입 로직 제거에 따른 테스트 실패 해결
<br><br>
```java
// src/test/java/com/ludo/study/studymatchingplatform/config
@Component
@RequiredArgsConstructor
public class DbInitializer {
private final CategoryRepositoryImpl categoryRepository;
private final PositionRepositoryImpl positionsRepository;
@PostConstruct
public void init() {
initCategories();
initPositions();
}
private void initCategories() {
saveCategories(
Category.builder()
.name("프로젝트")
.build(),
Category.builder()
.name("코딩 테스트")
.build(),
Category.builder()
.name("모의 면접")
.build()
);
}
private void saveCategories(Category... categories) {
for (Category category : categories) {
categoryRepository.save(category);
}
}
private void initPositions() {
savePositions(
Position.builder()
.name("백엔드")
.build(),
Position.builder() …
```
=> Fix: @PostConstructor 데이터 삽입 로직 제거에 따른 테스트 실패 해결

src/main/java/com/ludo/study/studymatchingplatform/common/advice/CommonResponseAdvice.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentService.java, src/test/java/com/ludo/study/studymatchingplatform/study/fixture/recruitment/RecruitmentFixture.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentServiceTest.java, src/test/resources/application.yaml
- 스터디 지원자 거절시 재지원 불가 하도록 수정했습니다.
- 스웨거 정상적으로 작동하도록 수정했습니다.
<br><br>
- **지원자 거절시 재지원 불가**
스터디 지원시 존재하는 기록이 있을 경우 상태를 기준으로 예외를 반환하도록 하여 이슈를 해결했습니다. 
<br><br>
- **스웨거 정상화**
이슈의 원인은 swagger-ui 요청 body가 `CommonResponse`에 담기는 것 이었습니다. 
요청 URL은 `/v3/api-docs`였으며, 해당 URL을 `CommonResponseAdvice`의 검증 항목에서 제외하도록 하여 이슈를 해결했습니다.
<br><br>
=> Sp-384/Refactor: 지원자 거절시 재지원 불가 / 스웨거 정상화

build.gradle, src/main/resources/application.yaml
<br><br>
- (없다면 이 문항을 지워주세요.)
1. Prometheus 의존성 추가
```gradle
// build.gradle
dependencies {
// ...
runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
}
```
2. application.yaml 설정 추가
```yaml
management:
info:
java:
enabled: true
os:
enabled: true
env:
enabled: true
build:
enabled: true
defaults:
enabled: true
endpoint:
health:
show-components: always
prometheus:
enabled: true
endpoints:
web:
exposure:
include: "*"
server:
port:
${METRIC_PORT:9999}
server:
port: ${PORT}
tomcat:
mbeanregistry:
enabled: true
```
기본적인 metric들을 노출시켰으며,
metric endpoint는 api와 별개의 PORT(9999)로 설정하였습니다.
metric 정보에 아무나 접근할 수 없도록 public network로 노출시키지 않고 VPC를 통해 WAS와 private subnet을 통해 metric을 수집하기 위함입니다.
<br><br>
- 모니터링 서버 연결 필요
https://github.com/Ludo-SMP/ludo-backend-monitoring/pull/1
<br><br>
---
was에서 …
=> SP-401/Feat: prometheus 의존성 추가 및 설정

build.gradle, src/main/java/com/ludo/study/studymatchingplatform/auth/common/provider/CookieProvider.java, src/main/java/com/ludo/study/studymatchingplatform/auth/common/provider/JwtTokenProvider.java, src/main/java/com/ludo/study/studymatchingplatform/auth/common/redis/UserDetails.java, src/main/java/com/ludo/study/studymatchingplatform/auth/common/service/UserDetailsService.java, src/main/java/com/ludo/study/studymatchingplatform/auth/common/util/Headers.java, src/main/java/com/ludo/study/studymatchingplatform/auth/common/util/WebUtils.java, src/main/java/com/ludo/study/studymatchingplatform/auth/controller/google/GoogleLoginController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/controller/google/GoogleSignUpController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/controller/kakao/KakaoLoginController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/controller/kakao/KakaoSignUpController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/controller/naver/NaverLoginController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/controller/naver/NaverSignUpController.java, src/main/java/com/ludo/study/studymatchingplatform/auth/repository/UserDetailsRepository.java, src/main/java/com/ludo/study/studymatchingplatform/auth/service/kakao/KakaoSignUpService.java, src/main/java/com/ludo/study/studymatchingplatform/common/advice/CommonResponseAdvice.java, src/main/java/com/ludo/study/studymatchingplatform/common/properties/ClientProperties.java, src/main/java/com/ludo/study/studymatchingplatform/config/RedisConfig.java, src/main/java/com/ludo/study/studymatchingplatform/config/ServletFilterConfig.java, src/main/java/com/ludo/study/studymatchingplatform/filter/JwtAuthenticationFilter.java, src/main/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentService.java, src/main/java/com/ludo/study/studymatchingplatform/user/controller/UserController.java, src/main/java/com/ludo/study/studymatchingplatform/user/service/UserService.java, src/main/resources/application-dev.yaml, src/main/resources/application.yaml, src/test/java/com/ludo/study/studymatchingplatform/study/fixture/recruitment/RecruitmentFixture.java, src/test/java/com/ludo/study/studymatchingplatform/study/service/recruitment/RecruitmentServiceTest.java, src/test/resources/application.yaml
- **별도의 인스턴스로 redis 서버 생성**
- 현재 운영중인 java 서버로 통합을 고민했으나, 1gb라는 한정된 자원에서 지속적으로 늘어날 사용자 수를 고려했을 때 scale-out이 옳다고 판단했습니다. 
<br><br>
- **사용자 accessToken refresh 로직 추가**
- 서비스에 지속적인 접근을 원하는 사용자의 안전한 토큰 갱신 목적
- 단순히 refreshToken을 적용하는 방법으로는 보안상의 이점 없이 accessToken을 연장 시키는 것 밖에 되지 않는다고 판단하여 특정 할 수 있는 사용자 식별 정보를 활용하는 방법을 채택했습니다.
- userAgent 헤더 / clientIp 활용 (refreshToken 방식 X)
- redis서버에서 동작하도록 하여 chache hit를 통한 성능 향상
<br><br>
- **고려한 보안 사항**
- **중간자 공격(MITM Attack) - 네트워크 통신을 조작하여 통신 내용을 훔쳐 보거나 조작하는 공격 유형.**
- 기존에 적용된 Secure 속성 사용으로 해결했습니다. HTTPS를 사용하면 모든 통신 내용은 암호화되기 때문에 공격자의 중간자 공격을 통한 토큰 탈취를 방지할 수 있습니다.
- **XSS(Cross-Site Scripting) - 대상 웹사이트에 악성 스크립트를 주입하여 비정상적인 동작을 실행시키는 공격 유형.**
- HttpOnly 속성 사용으로 해결했습니다. HttpOnly 속성은 웹브라우저가 스크립트를 통한 Dom document.cookie 객체 접근을 허용하지 않도록 합니다. 즉 공격자의 XSS를 통한 …
=> Sp-389/Feat: Redis에서 동작하는 토큰 리프레시 적용

docker-compose.yml
docker compose 설정 파일에 redis를 추가 하였습니다.
<br><br>
- [O] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [O] 커밋 메세지를 컨벤션에 맞추었습니다.
=> SP-447: docker-compose.yml에 redis 설정 추가
